name: New Workflow

on: [push]

jobs:
  simple-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Print a message
        run: echo "Hello, GitHub Actions!"
